### ISSUE TITLE
The file was created by one commit, was changed by the other commit, related to the same req. but the impact of the requirement on it is only 90%.

### ISSUE THREAD

**Issue by KatsiarynaK** [uv48uson/amos-ss15-proj3#124] opened 2015-07-01 07:01 UTC
The file amos-ss15-proj3-backend\src\main\java\de\fau\osr\core\vcs\impl\GitBlameOperation,java was created for the req 70. 
http://gyazo.com/c5f81a6857a1764037f35d5543c530fd

According to the system, it was changed by other commit related to the same req. But not all of its lines are correlated to the req 70. See the snapshot: 
http://gyazo.com/63e1fb396bef5dc7984831f4fa4d4dde

According to the Traceability Matrix, no other req., but only req 70 has impact on the file.

**Comment by TPolzer** [comment] 2015-07-01 07:18
I am not sure what is the expected behavior here. There are commits without requirement id (referencing issue #113) that touch that file. Should they be listed? My understanding was that only the commits relating to the selected requirement shall be listed.

**Comment by TPolzer** [comment] 2015-07-01 07:19
Is this possibly the same defect as #91? @yadimon?

**Comment by TPolzer** [comment] 2015-07-01 07:25
Closing as duplicate of #100. It is the same issue, just that in one case all the commits did not have the corresponding requirement.

**Comment by KatsiarynaK** [comment] 2015-07-01 07:25
@TPolzer You are right, "My understanding was that only the commits relating to the selected requirement shall be listed" !true! But the problem is not with the listed commits. Several commits which relate to the file are listed.


The problem is that the total affect on the file is only 90%. but it must be 100% in total for each file. And not all code lines are correlated with the req

**Comment by TPolzer** [comment] 2015-07-01 07:26
It cannot be 100% because there are lines which were not linked to that requirement.

**Comment by TPolzer** [comment] 2015-07-01 07:27
Look at
```
git log --word-diff=color -p ./amos-ss15-proj3-backend/src/main/java/de/fau/osr/core/vcs/impl/GitBlameOperation.java
```

**Comment by KatsiarynaK** [comment] 2015-07-01 07:32
Sorry, but I dont understand what it means:
git log --word-diff=color -p ./amos-ss15-proj3-backend/src/main/java/de/fau/osr/core/vcs/impl/GitBlameOperation.java

:)

But why:
"It cannot be 100% because there are lines which were not linked to that requirement". ???

according to the traceability matrix, the file is only connected with the req 70

**Comment by TPolzer** [comment] 2015-07-01 08:16
Closed after discussion with @KatsiarynaK.

**Closed** 2015-07-01 08:15 UTC
