### ISSUE TITLE
multiple call of "add linkage" after multiple refreshes

### ISSUE THREAD

**Issue by yadimon** [uv48uson/amos-ss15-proj3#140] opened 2015-07-06 21:55 UTC
in the app, click multiple time on some refresh buttons.
try to add linkage on "Linkage Management" tab.
you will see multiple message boxes "added"

**Comment by TPolzer** [comment] 2015-07-06 21:57
Duplicate of #133, this is a general issue on reconfiguration (no matter if from configuration or refresh button).

**Closed by TPolzer** 2015-07-06 21:57 UTC
Labels: bug
