### ISSUE TITLE
navigate from files. Some files have no commit

### ISSUE THREAD

**Issue by yadimon** [uv48uson/amos-ss15-proj3#91] opened 2015-06-22 14:42 UTC
Gui: navigate from file.
click on first (pom.xml) -> many requirements.

click on some real file we have, like *"amos-ss15-proj3-backend\src\main\java\de\fau\osr\core\db\DBOperation.java"*
no commits in list.

the method of `GitVcsClient.java#getCommitListForFileodification()`
returns empty list(iterator) of commits for *"amos-ss15-proj3-backend\src\main\java\de\fau\osr\core\db\DBOperation.java"* path.

**Comment by KatsiarynaK** [comment] 2015-07-01 07:29
@TPolzer 
Yes, probably the issue #100 is duplicate with this one.

But the problem is still here. The build I am testing was made at 8. a.m.

**Comment by TPolzer** [comment] 2015-07-13 14:22
This is kind of fixed. While there are now commits for every file, the logic behind it is very simple, so it does not detect any moved files. Closing, as we have enough other issues to work out until release.

**Closed by TPolzer** 2015-07-13 14:22 UTC
Labels: bug
