### ISSUE TITLE
Req63: Traceability matrix, more digits still display after comma

### ISSUE THREAD

**Issue by kaobizz** [uv48uson/amos-ss15-proj3#106] opened 2015-06-24 09:17 UTC
As a user, I want to see only one digit after the comma so that the GUI is not too cluttered.

**Comment by TPolzer** [comment] 2015-06-24 09:36
duplicate of #96

**Comment by gayathery** [comment] 2015-06-27 15:17
https://github.com/uv48uson/amos-ss15-proj3/commit/2c5888f01b8383e626cd2d0ec8822136e3e2af6f

**Closed by gayathery** 2015-06-27 15:17 UTC
Labels: bug
