### ISSUE TITLE
Wrong lines are shown for requirement impact

### ISSUE THREAD

**Issue by gayathery** [uv48uson/amos-ss15-proj3#114] opened 2015-06-27 16:38 UTC
Sometimes some lines are shown to be  changed for a requirement but that line was not modified for that requirement. A sample is shown in the image below.
![newblamelogic_bug2](https://cloud.githubusercontent.com/assets/11977313/8392971/9b880cee-1cfb-11e5-9413-d0a94a8b8b47.png)

**Comment by TPolzer** [comment] 2015-06-27 16:52
Duplicate of #112. Closing.

**Comment by gayathery** [comment] 2015-06-27 17:21
This is not in fact a duplicate of #112 but this is a difference issue. This issue deals with showing a requirement which modified the line in the past but the words in the current line are no way related to it and #112 is related to showing a line which was not at all changed for that requirement. The impact percentage is wrongly calculated because of this and the difference in impact percentage because of the two issues are different to each other.

**Comment by TPolzer** [comment] 2015-06-27 17:24
If you read my comment in #112  you would see that it is exactly the same problem. I said there:
"[...] the current interpretation of the word wise logic is that 'de.fau.osr.core.vcs.impl.GitBlameOperation;\nimport ' was inserted for that requirement.".
Both observations you made stem from this one single issue.

**Comment by gayathery** [comment] 2015-06-27 17:27
I accept that the source of the issue might be the same, but from the user point of view, these are two different issues..we dont know whether a solution to one issue solves the other. so it is better to keep the issue under tracking until both problems are solved from user perspective

**Comment by TPolzer** [comment] 2015-06-27 19:50
It is the same issue. I know.

**Closed** 2015-06-29 06:26 UTC
Labels: bug
